// <auto-generated />
namespace CRUDVibe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabeladeEndereçosemudançanaspropriedadescorreção2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabeladeEndereçosemudançanaspropriedadescorreção2));
        
        string IMigrationMetadata.Id
        {
            get { return "202109271813480_Tabela de Endereços e mudança nas propriedades correção 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
